<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Event Request Submitted</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .details {
            background-color: #fff;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
        }
        .detail-row {
            margin-bottom: 10px;
            padding-bottom: 10px;
            border-bottom: 1px solid #eee;
        }
        .detail-row:last-child {
            border-bottom: none;
        }
        .label {
            font-weight: bold;
            color: #495057;
            display: inline-block;
            width: 120px;
        }
        .action-button {
            display: inline-block;
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px 5px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            color: #6c757d;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎉 New Event Request Submitted</h1>
        <p>A new event organization request has been submitted and requires your review.</p>
    </div>

    <div class="details">
        <h2>Organizer Details</h2>

        <div class="detail-row">
            <span class="label">Organizer Name:</span>
            <span>{{ $organizer->name }}</span>
        </div>

        <div class="detail-row">
            <span class="label">Email Address:</span>
            <span><a href="mailto:{{ $organizer->email }}">{{ $organizer->email }}</a></span>
        </div>

        <div class="detail-row">
            <span class="label">Contact Number:</span>
            <span>{{ $organizer->contact }}</span>
        </div>

        <div class="detail-row">
            <span class="label">Event Name:</span>
            <span><strong>{{ $organizer->event_name }}</strong></span>
        </div>

        <div class="detail-row">
            <span class="label">Event Type:</span>
            <span>{{ $organizer->event_type }}</span>
        </div>

        @if(!empty($organizer->event_date))
        <div class="detail-row">
            <span class="label">Event Date:</span>
            <span>{{ \Carbon\Carbon::parse($organizer->event_date)->format('F j, Y') }}</span>
        </div>
        @endif

        @if(!empty($organizer->event_location))
        <div class="detail-row">
            <span class="label">Event Location:</span>
            <span>{{ $organizer->event_location }}</span>
        </div>
        @endif

        @if(!empty($organizer->description))
        <div class="detail-row">
            <span class="label">Event Description:</span>
            <span>{{ $organizer->description }}</span>
        </div>
        @endif
    </div>

    <div style="text-align: center; margin: 30px 0;">
        <h3>Take Action</h3>
        <a href="{{ url('/admin/organizers') }}" class="action-button" style="background-color: #28a745">View Full Details</a>
    </div>

    <div class="footer">
        <p>This notification was automatically generated by the Event Management System.</p>
        <p>If you believe you received this email in error, please contact the system administrator.</p>
        <p>© {{ date('Y') }} Your Company Name. All rights reserved.</p>
    </div>
</body>
</html>
